#cloud-config
package_upgrade: true
packages:
 - python-pip
 - unzip
runcmd:
 - sudo pip install awscli
 - cd /home/ubuntu
 - aws s3 cp s3://ompa.olem.org/dist/ompa-BUILD_NUMBER.tar ompa.tar --region=eu-west-1
 - chown ubuntu:ubuntu ompa.tar
 - sudo -u ubuntu tar -xvf ompa.tar
 - cd /home/ubuntu/bin
 - sudo -u ubuntu ./start.sh MONGO_URI