name: ompa
description: A sample web application
dependencies:
  angular: any
  browser: any
  bson: any
  crypto: any
  di: any
  http_utils: any
  intl: any
  mongo_dart: any
dev_dependencies:
  unittest: any
